### PR TITLE
add(about-me-section)

### PR DESCRIPTION
**Pull request by slava89**

### CODE REVIEW

**Comment by andrewdacenko** [comment]
@slava89 One paragraph is not enough

**Comment by slava89** [comment]
@JackLip suggest what to add more in about me page

**Comment by andrewdacenko** [comment]
@br-dr/brdr add proper link thus page will scroll into view of section

**Comment by andrewdacenko** [comment]
@br-dr/brdr please skip content issues - concentrate on links

**Comment by slava89** [comment]
Do i need to use some jquery to implement smooth scrolling, or just a basic href links?

**Comment by andrewdacenko** [comment]
@slava89 Use simple link

**Comment by andrewdacenko** [comment]
close #4

**Pull request merged**
